[tox]
envlist =
  py{39,310,311,312}-dj32,
  py{39,310,311,312}-dj40,
  py{39,310,311,312}-dj41,
  py{39,310,311,312,313}-dj42,
  py{312,313}-dj52,
  flake8,
  isort,
  readme,
  check-manifest

[gh-actions]
python =
  3.9: py39
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313

[testenv]
passenv = TOXENV, CI, TRAVIS, TRAVIS_*, CODECOV_*
deps =
  dj32: Django>=3.2,<4.0
  dj40: Django>=4.0,<4.1
  dj41: Django>=4.1,<4.2
  dj52: Django>=5.2,<5.3

  django-pymemcache<2.0
  djdev: https://github.com/django/django/archive/master.tar.gz
  -r{toxinidir}/requirements.txt
  py312-dj52: codecov
setenv =
  PYTHONPATH = {toxinidir}
commands =
  coverage run --source=django_elastipymemcache -m pytest --verbose
  py312-dj52: coverage report
  py312-dj52: coverage xml
  py312-dj52: codecov

[testenv:flake8]
skip_install = true
basepython = python3.12
commands = flake8
deps = flake8

[testenv:isort]
skip_install = true
basepython = python3.12
commands = isort --verbose --check-only --diff django_elastipymemcache tests setup.py
deps = isort

[testenv:readme]
skip_install = true
basepython = python3.12
commands = python setup.py check -r -s
deps =
  readme_renderer
  setuptools

[testenv:check-manifest]
skip_install = true
basepython = python3.12
commands = check-manifest {toxinidir}
deps = check-manifest
